name: mpv clang
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Run custom command before building'
        required: false
        type: string
      github_release:
        description: 'Upload to Github release'
        required: false
        default: true
        type: boolean
      mpv_tarball:
        description: 'Build latest mpv tarball'
        required: false
        default: false
        type: boolean

jobs:
  build_mpv:
    name: Building mpv
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    strategy:
      fail-fast: false
      matrix:
        bit: [i686, x86_64, x86_64_v3, aarch64]
    env:
      BIT: ${{ matrix.bit }}
    container:
      image: docker://ghcr.io/shinchiro/archlinux:latest
    outputs:
      mpv_ver: ${{ steps.build_mpv_step.outputs.mpv_ver }}
    steps:
      - name: Init variable
        run: |
          if [[ $BIT == "i686" ]]; then
            echo "arch=i686" >> $GITHUB_ENV
          elif [[ $BIT == "x86_64" ]]; then
            echo "arch=x86_64" >> $GITHUB_ENV
          elif [[ $BIT == "x86_64_v3" ]]; then
            echo "arch=x86_64" >> $GITHUB_ENV
            echo "x86_64_level=-v3" >> $GITHUB_ENV
            echo "x86_64_v3_ARCH=-DGCC_ARCH=x86-64-v3" >> $GITHUB_ENV
          elif [[ $BIT == "aarch64" ]]; then
            echo "arch=aarch64" >> $GITHUB_ENV
          fi

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main

      - name: Loading clang sysroot cache
        uses: actions/cache/restore@main
        with:
          path: |
            clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Loading repository cache
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-repository

      - name: Loading ${{ matrix.bit }} toolchain cache
        uses: actions/cache/restore@main
        with:
          path: |
            build_${{ matrix.bit }}
          key: ${{ secrets.CACHE_VERSION }}-clang-${{ matrix.bit }}_toolchain-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-clang-${{ matrix.bit }}_toolchain

      - name: Running custom command
        if: ${{ github.event.inputs.command != '' }}
        continue-on-error: true
        run: ${{ github.event.inputs.command }}

      - name: Configuring CMake & Downloading source
        run: |
          cmake -DTARGET_ARCH=${{ env.arch }}-w64-mingw32 -DCOMPILER_TOOLCHAIN=clang ${{ env.x86_64_v3_ARCH }} -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_$BIT/$BIT-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -DENABLE_CCACHE=ON -DCLANG_PACKAGES_LTO=ON -G Ninja --fresh -B build_$BIT -S $PWD
          ninja -C build_$BIT download || true

      - name: Building mpv
        id: build_mpv_step
        env:
          MPV_TARBALL: ${{ github.event.inputs.mpv_tarball }}
        run: |
          ninja -C build_$BIT update
          $MPV_TARBALL && ninja -C build_$BIT mpv-release || ninja -C build_$BIT mpv
          $MPV_TARBALL && echo "mpv_ver=$(cat build_$BIT/packages/mpv-release-prefix/MPV_VERSION)" >> $GITHUB_OUTPUT || echo "mpv_ver=UNKNOWN" >> $GITHUB_OUTPUT

      - name: Packaging mpv
        run: |
          mkdir -p release_$BIT
          ninja -C build_$BIT mpv-packaging; mv build_$BIT/mpv*.7z release_$BIT


      - name: Collecting logs
        if: always()
        run: |
          mkdir -p build_${BIT}_logs
          cp -fr $(find build_$BIT -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log") build_${BIT}_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z build*logs

      - name: Uploading logs
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: logs-${{ matrix.bit }}
          path: logs.7z

      - name: Uploading ${{ matrix.bit }} build
        uses: actions/upload-artifact@master
        with:
          name: mpv-${{ matrix.bit }}
          path: |
            release_${{ matrix.bit }}/mpv-*${{ env.arch }}*
            !release_${{ matrix.bit }}/mpv-debug-*
            !release_${{ matrix.bit }}/mpv-dev-*


  release:
    name: Upload releases
    runs-on: ubuntu-latest
    needs: build_mpv
    permissions:
      contents: write
    steps:
      - name: Download releases
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          pattern: mpv-*

      - name: Release
        if: ${{ github.event.inputs.github_release == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          TAG: ${{ needs.build_mpv.outputs.mpv_ver }}
        run: |
          TAG=${TAG/UNKNOWN/dev}
          if gh release edit $TAG --title $TAG --target $GITHUB_REF_NAME --draft; then
            gh release view $TAG --json assets --jq '.assets[].name' |
              while read -r NAME; do gh release delete-asset $TAG $NAME; done
            gh release upload $TAG *
          else
            gh release create $TAG --title $TAG --target $GITHUB_REF_NAME --draft *
          fi
